#Requires -Version 7
<#
.SYNOPSIS
    Writes a Dependabot configuration file to the target repository.

.DESCRIPTION
    Creates or updates .github/dependabot.yml in the target repo, configured for:
    - npm packages: weekly, target master branch, grouped minor/patch updates
    - github-actions: weekly
    - docker: weekly

.ENVIRONMENT VARIABLES
    GITHUB_TOKEN  - PAT with 'repo' scope
    GITHUB_OWNER  - GitHub username or organization
    REPO_NAME     - Target repository name
    TARGET_BRANCH - Branch to target for updates (default: master)

.NOTES
    Idempotent: updates existing file if present.
    Author: gh-repo-bootstrap
    Version: 1.0.0
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Header {
    param([string]$Title)
    Write-Host ""; Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  $Title" -ForegroundColor Cyan; Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
}

function Get-Credential-Env {
    param([string]$EnvName, [string]$Prompt, [switch]$Secret)
    $val = [System.Environment]::GetEnvironmentVariable($EnvName)
    if (-not $val) {
        if ($Secret) {
            $secure = Read-Host -Prompt $Prompt -AsSecureString
            $val = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
                [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure))
        }
        else { $val = Read-Host -Prompt $Prompt }
    }
    return $val
}

function Push-RepoFile {
    param([string]$Owner, [string]$Repo, [string]$RepoPath, [string]$Content, [string]$CommitMsg, [string]$Token, [string]$Branch = 'main')

    $encoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($Content))
    $uri = "https://api.github.com/repos/$Owner/$Repo/contents/$RepoPath"
    $headers = @{
        'Authorization' = "Bearer $Token"; 'Accept' = 'application/vnd.github+json'
        'X-GitHub-Api-Version' = '2022-11-28'
    }
    $existingSha = $null
    try { $existingSha = (Invoke-RestMethod -Uri $uri -Method GET -Headers $headers).sha } catch {}

    $body = @{ message = $CommitMsg; content = $encoded; branch = $Branch }
    if ($existingSha) { $body['sha'] = $existingSha }
    Invoke-RestMethod -Uri $uri -Method PUT -Headers $headers `
        -Body ($body | ConvertTo-Json -Depth 5) -ContentType 'application/json' | Out-Null
    return if ($existingSha) { 'updated' } else { 'created' }
}

# ─── Main ─────────────────────────────────────────────────────────────────────

Write-Header "08 — Dependabot"

$TOKEN = Get-Credential-Env -EnvName 'GITHUB_TOKEN'  -Prompt 'GitHub PAT' -Secret
$OWNER = Get-Credential-Env -EnvName 'GITHUB_OWNER'  -Prompt 'GitHub owner'
$REPO_NAME = Get-Credential-Env -EnvName 'REPO_NAME'     -Prompt 'Repository name'
$TARGET_BRANCH = if ($env:TARGET_BRANCH) { $env:TARGET_BRANCH } else { 'master' }

$stats = @{ created = 0; skipped = 0; errors = 0 }

$dependabotContent = @"
# Dependabot configuration
# Generated by gh-repo-bootstrap
# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:

  # ── npm ────────────────────────────────────────────────────────────────────
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: "$TARGET_BRANCH"
    open-pull-requests-limit: 10
    labels:
      - "type: chore"
      - "epic: infrastructure"
      - "P3: low"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Pin major version upgrades for manual review
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "$OWNER"
    assignees:
      - "$OWNER"

  # ── github-actions ─────────────────────────────────────────────────────────
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: "$TARGET_BRANCH"
    open-pull-requests-limit: 5
    labels:
      - "type: chore"
      - "epic: infrastructure"
      - "P3: low"
    commit-message:
      prefix: "ci(actions)"
      include: "scope"

  # ── docker ─────────────────────────────────────────────────────────────────
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: "$TARGET_BRANCH"
    open-pull-requests-limit: 5
    labels:
      - "type: chore"
      - "epic: infrastructure"
      - "P2: medium"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
"@

Write-Host "  → Writing .github/dependabot.yml..." -ForegroundColor Gray
try {
    $result = Push-RepoFile -Owner $OWNER -Repo $REPO_NAME -RepoPath '.github/dependabot.yml' `
        -Content $dependabotContent -CommitMsg 'chore: add dependabot config via gh-repo-bootstrap' -Token $TOKEN
    if ($result -eq 'created') {
        Write-Host "  ✅ Created: .github/dependabot.yml" -ForegroundColor Green; $stats.created++
    }
    else {
        Write-Host "  ⏭️  Updated: .github/dependabot.yml" -ForegroundColor Yellow; $stats.skipped++
    }
}
catch {
    Write-Host "  ❌ Failed: $_" -ForegroundColor Red; $stats.errors++
}

Write-Host ""; Write-Host "─── Summary ─────────────────────────────" -ForegroundColor DarkGray
Write-Host "  ✅ Created : $($stats.created)" -ForegroundColor Green
Write-Host "  ⏭️  Updated : $($stats.skipped)" -ForegroundColor Yellow
Write-Host "  ❌ Errors  : $($stats.errors)" -ForegroundColor Red; Write-Host ""
if ($stats.errors -gt 0) { exit 1 }
