#!/usr/bin/env bash
# ==============================================================================
# setup_dependabot.sh — Writes dependabot.yml to target repo
# Part of gh-repo-bootstrap | Version: 1.0.0
#
# SYNOPSIS
#   Automates dependency management via GitHub Dependabot.
#
# DESCRIPTION
#   Creates `.github/dependabot.yml` configured for weakly updates against
#   npm, GitHub Actions, and Docker. Applies custom labels and commit prefixes
#   to all automated pull requests to maintain a clean git history.
#
# ENVIRONMENT VARIABLES
#   GITHUB_TOKEN   - PAT with 'repo' scope
#   GITHUB_OWNER   - GitHub username or organization name
#   REPO_NAME      - Target repository name
#   TARGET_BRANCH  - Default branch to target updates (default: 'master')
#
# NOTES
#   Idempotent operation. See OPERATIONS_MANUAL.md for additional details.
# ==============================================================================
set -euo pipefail

for dep in curl jq base64; do
  command -v "$dep" &>/dev/null || { echo "❌ '$dep' not found." >&2; exit 1; }
done

print_header() {
  echo ""; echo "═══════════════════════════════════════"
  echo "  08 — Dependabot"; echo "═══════════════════════════════════════"
}

print_header
[[ -z "${GITHUB_TOKEN:-}" ]] && read -rsp "GitHub PAT: " GITHUB_TOKEN && echo
[[ -z "${GITHUB_OWNER:-}" ]] && read -rp  "GitHub owner: " GITHUB_OWNER
[[ -z "${REPO_NAME:-}"    ]] && read -rp  "Repository name: " REPO_NAME
TARGET_BRANCH="${TARGET_BRANCH:-master}"

CREATED=0; SKIPPED=0; ERRORS=0

CONTENT=$(cat <<EOF
# Dependabot configuration — generated by gh-repo-bootstrap
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: "${TARGET_BRANCH}"
    open-pull-requests-limit: 10
    labels: ["type: chore", "epic: infrastructure", "P3: low"]
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "${TARGET_BRANCH}"
    labels: ["type: chore", "epic: infrastructure", "P3: low"]
    commit-message:
      prefix: "ci(actions)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "${TARGET_BRANCH}"
    labels: ["type: chore", "epic: infrastructure", "P2: medium"]
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
EOF
)

URI="https://api.github.com/repos/${GITHUB_OWNER}/${REPO_NAME}/contents/.github/dependabot.yml"
ENCODED=$(printf '%s' "$CONTENT" | base64 | tr -d '\n')
SHA=$(curl -sf -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github+json" "$URI" 2>/dev/null | jq -r '.sha // empty' || echo "")

MSG="chore: add dependabot config via gh-repo-bootstrap"
if [[ -n "$SHA" ]]; then
  BODY=$(jq -n --arg m "$MSG" --arg c "$ENCODED" --arg s "$SHA" \
    '{message:$m, content:$c, branch:"main", sha:$s}')
else
  BODY=$(jq -n --arg m "$MSG" --arg c "$ENCODED" \
    '{message:$m, content:$c, branch:"main"}')
fi

echo "  → Writing .github/dependabot.yml..."
if curl -sf -X PUT -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" \
  -d "$BODY" "$URI" > /dev/null; then
  [[ -n "$SHA" ]] && { echo "  ⏭️  Updated: .github/dependabot.yml"; SKIPPED=$((SKIPPED+1)); } \
                  || { echo "  ✅ Created: .github/dependabot.yml"; CREATED=$((CREATED+1)); }
else
  echo "  ❌ Failed to write dependabot.yml"; ERRORS=$((ERRORS+1))
fi

echo ""; echo "─── Summary ─────────────────────────────"
echo "  ✅ Created : ${CREATED}"
echo "  ⏭️  Updated : ${SKIPPED}"
echo "  ❌ Errors  : ${ERRORS}"; echo ""
[[ "$ERRORS" -gt 0 ]] && exit 1 || exit 0
